baseURL = 'https://weebzone.github.io/'
languageCode = 'en-us'
title = 'WZML-X Docs | A PowerPacked Telegram Multi-Utility Bot'
contentDir = "content"
enableEmoji = true

[module]
    [module.hugoVersion]
      extended = true
      min = "0.100.0"
    [[module.imports]] 
        path = "github.com/colinwilson/lotusdocs" 
        disable = false
    [[module.imports]] 
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5" 
        disable = false

[markup.goldmark.renderer] 
    unsafe = true 

[[menu.primary]] 
    name = "Docs" 
    url = "/docs/"
    identifier = "docs"
    weight = 5

[params]

  google_fonts = [
    ["Inter", "300, 400, 600, 700"],
    ["Fira Code", "500, 700"]
  ]

  sans_serif_font = "Inter"
  secondary_font  = "Inter"

    [params.footer]
        copyright = "© :YEAR: WZML-X. All Rights Reserved"
        version   = true

    [params.social]
        github = "weebzone/WZML-X"

    [params.docs]
        title           = "WZML-X Guide & Docs"                        # default html title for documentation pages/sections
        # pathName        = "docs"                            # path for documentation site | default "docs"
        themeColor      = "cyan"                              # (optional) - Set theme accent colour. Options include: blue (default), green, red, yellow, emerald, cardinal, magenta, cyan
        darkMode        = true                                # enable dark mode option? default false
        prism           = true                                # enable syntax highlighting via Prism
        # prismTheme      = "lotusdocs"                         # (optional) - Set theme for PrismJS. Options include: lotusdocs (default), solarized-light, twilight, lucario

        # gitinfo
        repoURL         = "https://github.com/weebzone/weebzone.github.io"  # Git repository URL for your site [support for GitHub, GitLab, and BitBucket]
        repoBranch      = "main"                           # Name of your Git repository branch
        editPage        = false                                # enable 'Edit this page' feature - default false
        lastMod         = true                                # enable 'Last modified' date on pages - default false
        lastModRelative = true                                # format 'Last modified' time as relative - default true

        # ToC
        toc             = true                                # enable table of contents? default is true
        tocMobile       = true                                # enable table of contents in mobile view? default is true
        scrollSpy       = true                                # enable scrollspy on ToC? default is true

        # icons
        sidebarIcons    = true                                # enable sidebar icons? default false
        titleIcon       = true                                # enable front matter icon title prefix? default is false

        # content navigation
        breadcrumbs     = true                                # default is true
        navDesc         = true                                # include front matter descriptions in Prev/Next navigation cards
        navDescTrunc    = 30                                  # Number of characters by which to truncate the Prev/Next descriptions

        listDescTrunc   = 100                                 # Number of characters by which to truncate the list card description
        backToTop       = true                                # enable back-to-top button? default true

        # front matter
        descriptions    = true                                # enable front matter descriptions under content title?

        # Link behaviour
        intLinkTooltip  = true                                # Enable a tooltip for internal links that displays info about the destination? default false
        # extLinkNewTab   = false                               # Open external links in a new Tab? default true
        logoLinkURL = "https://wzml.xyz"

